# Generated by Django 6.0 on 2026-01-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_crud_apis', '0002_alter_author_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pic',
            field=models.ImageField(blank=True, default='authors_pic/user.png', null=True, upload_to='authors_pic/'),
        ),
    ]
